// Generated by CoffeeScript 1.3.3
var ShakeBar,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ShakeBar = (function(_super) {

  __extends(ShakeBar, _super);

  function ShakeBar() {
    return ShakeBar.__super__.constructor.apply(this, arguments);
  }

  ShakeBar.prototype.viewAppended = function() {
    var _ref,
      _this = this;
    this.setClass("bar");
    this.addSubView(this.name = new KDView({
      tagName: "h2"
    }));
    this.addSubView(this.inner = new KDView);
    this.inner.setRandomBG();
    this.setName((_ref = this.getData()) != null ? _ref.name : void 0);
    return this.parent.on("ThereIsAWinner", function() {
      return clearInterval(interval);
    });
  };

  ShakeBar.prototype.setName = function(name) {
    if (name) {
      this.setClass("named");
    }
    return this.name.updatePartial(name || "empty");
  };

  ShakeBar.prototype.grow = function() {
    if (this.inner.getHeight() < this.getHeight()) {
      return this.inner.setHeight(this.inner.getHeight() + this.utils.getRandomNumber(50));
    }
  };

  ShakeBar.prototype.shrink = function() {};

  return ShakeBar;

})(KDView);
