// Generated by CoffeeScript 1.3.3
var ShakeController,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ShakeController = (function(_super) {

  __extends(ShakeController, _super);

  function ShakeController(options, data) {
    ShakeController.__super__.constructor.apply(this, arguments);
    this.players = {};
    this.addPlatform();
    this.addJoinView();
    this.connect();
  }

  ShakeController.prototype.connect = function() {};

  ShakeController.prototype.allowPlayerToStart = function() {};

  ShakeController.prototype.createInitialPlayers = function() {};

  ShakeController.prototype.addPlayer = function(name) {
    if (!this.players[name]) {
      this.players[name] = {
        name: name,
        score: 0
      };
      this.platform.addBar(this.players[name]);
      return this.players[name];
    } else {
      return false;
    }
  };

  ShakeController.prototype.removePlayer = function() {};

  ShakeController.prototype.addPlatform = function() {
    var container;
    container = this.getOptions().container;
    this.platform = new ShakePlatform({
      domId: "platform"
    });
    if (container) {
      return container.addSubView(this.platform);
    } else {
      return KDView.appendToDOMBody(this.platform);
    }
  };

  ShakeController.prototype.addJoinView = function() {
    var joinButton, joinView;
    KDView.appendToDOMBody(joinView = new KDView({
      cssClass: "join-view"
    }));
    return joinView.addSubView(joinButton = new KDButtonView({
      title: "Join the game!",
      cssClass: "punch",
      callback: this.showJoinModal.bind(this)
    }));
  };

  ShakeController.prototype.showJoinModal = function() {
    var controller, modal, utils,
      _this = this;
    controller = this;
    utils = this.utils;
    modal = new KDModalViewWithForms({
      title: "Join to shake :)",
      width: 500,
      height: "auto",
      tabs: {
        navigable: true,
        forms: {
          join: {
            callback: function(_arg) {
              var name;
              name = _arg.name;
              if (_this.addPlayer(name)) {
                modal.destroy();
                return controller.allowPlayerToStart();
              } else {
                modal.modalTabs.forms["join"].buttons["I wanna shake, take me in!"].hideLoader();
                return new KDNotificationView({
                  title: 'Name taken, choose another name please!'
                });
              }
            },
            buttons: {
              "I wanna shake, take me in!": {
                type: "submit",
                loader: {
                  color: "#ffffff",
                  diameter: 20
                }
              }
            },
            fields: {
              name: {
                label: "Your name:",
                name: "name",
                placeholder: "type your name to start!"
              }
            }
          }
        }
      }
    });
    return modal.modalTabs.forms["join"].inputs.name.$().trigger("focus");
  };

  return ShakeController;

})(KDController);
