// Generated by CoffeeScript 1.3.3

(function() {
  var mainController;
  log("app started");
  KD.registerSingleton("windowController", new KDWindowController);
  return mainController = new ShakeController;
})();
